Cria componentes de formulário reutilizavéis
DadosAbertosDeFeira/portal pull request #124
Opened 2023-02-22 01:28 UTC by alvarogfn

## O que o Pull Request faz?

Separei os componentes de formulário do ContactForm em outros componentes, assim será possível reutiliza-los em outros componentes.

## Notas adicionais
Esse PR é contém uma parte do PR #121.

2023-05-06 22:28 UTC, matheusrocha89 commented on src/components/form/Textarea/Textarea.test.jsx
> +    const App = () => {
Eu moveria isso para um beforeEach para evitar repetir toda hora para instanciar o form: 

```javascript
describe("textarea", () => {
  let form;

  beforeEach(() => {
    form = useForm();
  });
  
  it('should renders Textarea component with required props', () => {
    const { getByPlaceholderText, container } = render(
      <Textarea
          name="username"
          label="Username"
          control={form.control}
          rules={{ required: true }}
        />
    );
  });
})
```

2023-05-06 22:30 UTC, matheusrocha89 commented on src/utils/validations/regexes.js
👍  Boa, essa separação de utils para validações é uma ótima ideia.

2023-05-06 22:32 UTC, matheusrocha89 commented on src/components/form/Textarea/Textarea.jsx
> +export default Textarea;
Os componentes eu acho melhor usarmos "named exports". Por quê eu acho isso? 
Named exports facilitam a identificação de onde eles são usados, porque o nome vai ser o mesmo em todo projeto. Se usarmos default exports qualquer pessoa pode colocar qualquer nome e se em algum momento precisarmos atualizar o component ou refatorar ele, fica mais difícil de fazer o tracking de onde ele está sendo usado. 

Melhor mudarmos de "default exports" para "named exports"

```javascript
export { Textarea };
```

2023-05-06 22:32 UTC, matheusrocha89 commented on src/components/form/Input/Input.jsx
> +export default Input;
Mudar para named exports

2023-05-06 22:33 UTC, matheusrocha89 requested changes
Fiz algumas sugestões, acho que ficaria melhor com as sugestões. 

Excelente trabalho no PR 👍

2023-05-06 22:34 UTC, matheusrocha89 commented on src/components/ContactForm/ContactForm.js
> -import { ErrorMessage } from '@hookform/error-message';
Se não vamos mais usar as "ErrorMessages" do @hookform melhor removermos o pacote do projeto.

2023-05-09 00:35 UTC, alvarogfn commented on src/components/form/Textarea/Textarea.test.jsx
> +    const App = () => {
Eu não consigo usar hooks fora de componentes funcionais sem usar libs, vou usar um pattern de factory para reutilizar.

2023-05-11 18:10 UTC, matheusrocha89 approved these changes
LGTM 👍

2023-05-11 18:37 UTC, merged