Adiciona suporte para typescript
DadosAbertosDeFeira/portal pull request #145
Opened 2023-05-21 17:17 UTC by alvarogfn

## O que o Pull Request faz?

Adiciona suporte para Typescript

## Issue relacionada
Closes #141

2023-05-21 23:11 UTC, alvarogfn commented on next.config.js
> +    ignoreDuringBuilds: true,
Tem que lembrar de remover isso aqui antes de mergear a branch na main, pois é só para vermos se os componentes estão renderizando direitinho na tela e se nada quebrou até migrarmos todos os componentes.

2023-05-22 22:39 UTC, matheusrocha89 requested changes

2023-05-22 22:39 UTC, matheusrocha89 commented on .gitignore
> -.vscode
Eu não tiraria o .vscode porque são configs específicas de cada dev. Por exemplo eu tenho outras configs específicas para plugins meus e outras coisas aqui, outro dev vai ter também uma diferente. Vai acabar conflitando e não deixando uma boa experiência de desenvolvimento para os contirbuidores

2023-05-22 22:39 UTC, matheusrocha89 commented on package.json
> +    "lint:staged": "next lint --lint-staged",
Chegou a testar esse comando com essa auteração? Porque lint-staged é uma package que usamos e não uma option de lint. Acho que não funciona assim.

2023-05-22 22:39 UTC, matheusrocha89 commented on .eslintrc.js
> +        singleQuote: true,
O que acha de colocarmos `doubleQuote`? Assim seguimos o "padrão" do mercado typescript no projeto.

2023-05-22 23:45 UTC, alvarogfn commented on .gitignore
> -.vscode
É, eu removi pois adicionei um code-workspace com algumas configurações predefinidas, achei que seria mais fácil para quem tá começando usar uma configuração plug-n-play sem precisar ficar configurando. O workspace eu acredito que só funcione se a pessoa abrir o projeto por ele, mas não tenho certeza, o que acha?

2023-05-22 23:48 UTC, alvarogfn commented on package.json
> +    "lint:staged": "next lint --lint-staged",
Vacilei, não vi que ainda tava o do next.

2023-05-23 06:05 UTC, anapaulagomes commented on .gitignore
> -.vscode
Nesse caso tu pode usar um gitignore global pra tu, @alvarogfn. Aqui explica como: https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

2023-05-23 14:39 UTC, matheusrocha89 commented on .eslintrc.js
> +            singleQuote: true,
Esqueci de comentar aqui também sobre o double quote

2023-05-23 14:42 UTC, matheusrocha89 commented on .eslintrc.js
> +        "@typescript-eslint/comma-dangle": "off", // Avoid conflict rule between Eslint and Prettier
Se usar o plugin de eslint to prettier ele automaticamente já remove os conflitos e não vamos precisar dessa regra

2023-05-23 14:43 UTC, matheusrocha89 commented on .eslintrc.js
> +        "@typescript-eslint/consistent-type-imports": "error", // Ensure `import type` is used when it's necessary
👍  Boa regra, muito boa

2023-05-23 14:43 UTC, matheusrocha89 commented on .eslintrc.js
> +        "import/prefer-default-export": "off", // Named export is easier to refactor automatically
Boa 👍

2023-05-23 14:44 UTC, matheusrocha89 commented on .eslintrc.js
> +        "@typescript-eslint/no-unused-vars": "off",
Essa a gente pode ligar, não vi nenhum cenário onde precisamos de variáveis declaradas e não utilizadas

2023-05-23 14:45 UTC, matheusrocha89 commented on .eslintrc.js
> +        "@typescript-eslint/no-unused-vars": "off",
Ahh, entendi, por conta do conflito com a de baixo. 

Humm... acho que podemos corrigir esses conflitos seguindo uma ordem no extends. Eu lembro que já vi isso em um artigo e funcionou bem. Vou só procurar onde foi

2023-05-23 14:49 UTC, matheusrocha89 commented on tsconfig.json
> +      "@/components/*": ["components/*"]
Aqui dá para fazer assim e ele automaticamente vai usar cada pasta como um alias, ajuda bastante:

```javascript
"baseUrl": ".",
"paths": {
  "@/*": ["./src/*"],
}

```

2023-05-23 14:55 UTC, matheusrocha89 commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
Esse package acho que não é necessário. Como nossos imports sempre são referenciando a uma variável, seja default ou seja nomeado, o "no-unused-vars" já pega isso para a gente.

2023-05-26 00:59 UTC, alvarogfn commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
Com esse plugin, o eslint --fix remove automaticamente imports não utilizados aparentemente.

2023-05-26 10:08 UTC, matheusrocha89 commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
Verdade, o no-unused-vars não tem o fix automático

2023-05-31 00:44 UTC, merged