Atualizar componentes para utilizar exclusivamente Tailwind, substituindo CSS Modules Fixes #142
DadosAbertosDeFeira/portal pull request #149
Opened 2023-05-28 14:30 UTC by alvarogfn

## O que o Pull Request faz?

* Remove o sass do projeto
* Remove todos os module.scss do projeto
* Remove o components.scss
* Remove o variables.scss

## Adicional

Vou corrigir os problemas do storybook na migração para o typescript.

## Issue relacionada
Closes #142

2023-05-29 09:04 UTC, matheusrocha89 requested changes
Os botões e os inputs ficaram diferentes dos atuais, devem estar faltando classes do tailwind neles:

Atuais:
<img width="419" alt="image" src="https://github.com/DadosAbertosDeFeira/portal/assets/3718366/d6b19272-3102-49d1-9fbc-585a5804949c">

Seu PR:
<img width="419" alt="image" src="https://github.com/DadosAbertosDeFeira/portal/assets/3718366/277cd69e-1e5a-402e-8292-3f58e86f4cb4">

2023-05-29 09:04 UTC, matheusrocha89 commented on src/components/Tag/Tag.jsx
> +    className={classNames(className, 'bg-[#f8f9fa] py-xs px-sm inline-block')}
Não precisa mudar nesse PR, mas depois vamos pensar em criar essas cores no tailwind config e trocar esses valores

2023-05-29 09:06 UTC, matheusrocha89 commented
Agora que você já a Ana já te colocou como contribuidor do projeto não precisa mais fazer as coisas dentro do teu fork, já pode criar branches e fazer direto aqui 👍 👏 

Deixei uns comentários, mas de resto excelente contribuição 👍 

![Obrigado](https://media.giphy.com/media/uWlpPGquhGZNFzY90z/giphy.gif)

2023-05-29 23:30 UTC, alvarogfn commented on src/components/Button/Button.jsx
> +        'font-semibold p-3 border rounded transition ease-in-out'
Só se eles tiverem width e height fixos, aí ele não fica centralizado, mas vou colocar por precaução

2023-05-29 23:33 UTC, alvarogfn commented on src/components/Tag/Tag.jsx
> +    className={classNames(className, 'bg-[#f8f9fa] py-xs px-sm inline-block')}
Beleza, @matheusrocha89, vamos precisar do toque de alguém do design para dizer quais são os tokens de cor importantes.

2023-05-30 08:21 UTC, matheusrocha89 requested changes
Só fui ver esse problema agora. Foi mal 😄

2023-05-30 08:21 UTC, matheusrocha89 commented on src/components/Tag/Tag.jsx
> +    className={classNames(className, 'bg-[#f8f9fa] py-xs px-sm inline-block')}
A propriedade `className` deve ser o último argumento se não for ela não vai sobrescrever outras classes e não vai fazer sentido tê-la

2023-05-30 08:21 UTC, matheusrocha89 commented on src/components/Button/Button.jsx
> +        className,
A propriedade `className` deve ser o último argumento se não for ela não vai sobrescrever outras classes e não vai fazer sentido tê-la

2023-06-02 16:07 UTC, matheusrocha89 approved these changes
LGTM 👍 
![Thanks](https://media.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif)

2023-06-02 16:23 UTC, merged