Documentação e informações importantes
DadosAbertosDeFeira/portal pull request #19
Opened 2020-11-21 18:16 UTC by olarclara

Esse PR contém as seguintes adições:

- Guia de contribuição: `/CONTRIBUTING.md`
- Código de conduta: `/CODE_OF_CONDUCT.md`
- Atualiza o `README.md` com links para os guias acima e lista os comandos disponíveis no repositório

2020-11-22 17:54 UTC, anapaulagomes requested changes
Excelente, @olarclara! Pedi uma alteração bem pequena. Depois dela estamos prontos pra o merge. 🎉

2020-11-22 17:54 UTC, anapaulagomes commented on CONTRIBUTING.md
> +  [grupo no Telegram](https://t.me/joinchat/DRT0JBcy-RUk2GJZCnH3Fg)
@olarclara pode substituir o Telegram pelo Discord, por favor? Vou fazer o mesmo no guia do Maria Quitéria.

2020-11-22 18:00 UTC, anapaulagomes commented on README.md
> +yarn
Será que compensa dizer que precisa do `npm`? 😅

2020-11-22 19:05 UTC, matheusrocha89 commented on README.md
> +yarn
Então......... acho que não né? 😄

2020-11-22 19:33 UTC, anapaulagomes commented on README.md
> +yarn
Não sei, na real. Eu mesmo não tinha instalado na minha máquina. :)

2020-11-23 11:54 UTC, olarclara commented on README.md
> +yarn
@anapaulagomes @matheusrocha89 acho que não, o yarn e o npm têm a mesma funcionalidade mas o projeto usa yarn e se alguém instalar com npm vai criar um lockfile diferente pra resolução de dependências e talvez causar conflito com o projeto.

2020-11-23 12:15 UTC, anapaulagomes commented on README.md
> +yarn
Hummm quando fui na página de instalação o comando sugerido pra instalar o yarn no Linux era com o npm. Agora entendi! Obrigada 😊

2020-11-23 13:24 UTC, olarclara commented on CONTRIBUTING.md
> +  [grupo no Telegram](https://t.me/joinchat/DRT0JBcy-RUk2GJZCnH3Fg)
@anapaulagomes atualizado! :)

2020-11-23 16:01 UTC, anapaulagomes approved these changes
🚀

2020-11-23 16:02 UTC, merged