Melhora responsividade do site
DadosAbertosDeFeira/portal pull request #60
Opened 2021-09-05 21:41 UTC by lucashanke

2021-09-06 08:10 UTC, matheusrocha89 commented
Boa @lucashanke quando tiver pronto me marca que eu faço review

2021-09-08 12:36 UTC, anapaulagomes approved these changes
🥇

2021-09-09 07:37 UTC, matheusrocha89 requested changes
@lucashanke Só precisa fazer a alteração do Link que eu falei. De resto tá show de bola. 👍

2021-09-09 07:37 UTC, matheusrocha89 commented on src/components/MobileMenu/MobileMenu.js
> +          <Link
@lucashanke Para os links externos o ideal é usar a tag `<a>` mesmo, assim evita qualquer problema com a navegação interna da app.

2021-09-09 07:37 UTC, matheusrocha89 commented on src/components/MobileMenu/MobileMenu.js
> +          <Link
Mesma coisa aqui também.

2021-09-09 07:37 UTC, matheusrocha89 commented on src/components/MobileMenu/MobileMenu.js
> +    };
👏 O que eu vejo de gente que esquece de fazer esse clean 👏 👏 👏 👏 👏 👏 👏

2021-09-09 07:41 UTC, matheusrocha89 commented
@lucashanke nem se preocupa com os links, eu já tenho um PR para isso, vou dar approve. E afinal de contas o contexto do seu PR é melhorar a responsividade do site, não tem nada haver com corrigir esses links. Deixa assim mesmo. Ficou show de bola o código.

2021-09-09 07:42 UTC, matheusrocha89 approved these changes

2021-09-09 07:43 UTC, matheusrocha89 commented
Só uma dúvida @anapaulagomes o Hamburger menu não ficaria melhor do lado esquerdo que nem é na maioria do sites?

2021-09-09 07:45 UTC, matheusrocha89 commented on src/components/Header/Header.js
> +      <button type="button" onClick={toggleMenu}>
O toggle não funciona, se clicar outra vez com o menu aberto ele não fecha.

2021-09-09 17:30 UTC, merged

2021-09-10 05:18 UTC, anapaulagomes commented on src/components/Header/Header.js
> +      <button type="button" onClick={toggleMenu}>
@matheusrocha89 rola abrir uma issue separada pra isso?

2021-09-10 07:32 UTC, matheusrocha89 commented on src/components/Header/Header.js
> +      <button type="button" onClick={toggleMenu}>
Rola sim, sem problemas 👍